In [1]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [2]:
#importing the required library
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import FunctionTransformer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.metrics import f1_score, accuracy_score
from sklearn import model_selection
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import metrics
import warnings
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
stop = stopwords.words('english')
warnings.filterwarnings("ignore")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adamameen/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adamameen/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [3]:
lemmatizer = WordNetLemmatizer()
def preprocessing(x):
  #first we make text to lowercase 
  x = x.apply(lambda x: " ".join(x.lower() for x in x.split()))
  #remove punctuation
  x = x.str.replace('[^\w\s]','')
  #removing stop workds
  x = x.apply(lambda x: " ".join(x for x in x.split() if x not in stop))
  #removing digits
  x = x.str.replace('\d+', '')
  #lemmatizing
  x = [lemmatizer.lemmatize(row) for row in x]
  return x

preprocessor = FunctionTransformer(preprocessing)

In [5]:
import joblib

In [6]:
pipeline = joblib.load('Rating_predictor.pkl')

In [10]:
pipeline.predict(pd.Series(['Hey this is the worst place i have been.','this is the best of the best. I love it','its okay, not the best but its okay','its satisfactory, not the best quality']))

array([1, 5, 4, 5])

In [11]:
pipeline.predict(pd.Series(["This is the worst food"]))

array([1])

In [14]:
pipeline.predict(pd.Series(["This is the worst service","The food is ok but the service was very good. The price was very affordable. Overall very great experience"]))

array([1, 4])

In [16]:
pipeline.predict(pd.Series(["Plese never go here!. The worst experience."]))

array([1])